CREATE TABLE IF NOT EXISTS USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS POSTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    BODY TEXT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
