spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/kodilla_tester?serverTimezone=Europe/Warsaw&useSSL=False}
spring.datasource.username=${DB_USERNAME:kodilla}
spring.datasource.password=${DB_PASSWORD:kodilla_password}

spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
